{% set name = "rpaframework-recognition" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rpaframework-recognition-{{ version }}.tar.gz
  sha256: 5fa73ce22f6a6d96f37b5335c50d7e566655bbf36ee8f57d33a4b38a2bde7a5d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<4.0
    - numpy 1.14.*
  run:
    - {{ pin_compatible('numpy') }}
    - opencv >=4.4.0,<5.0.0
    - pillow >=8.0.1,<9.0.0
    - pytesseract >=0.3.6,<0.4.0
    - python >=3.6,<4.0
    - rpaframework-core >=4.0.1,<5.0.0
    - tesseract >=4.1.1,<5.0.0

test:
  imports:
    - RPA
    - RPA.recognition
    # The package's requirements.txt has a different, too narrow numpy specification
    # commands:
      # - pip check
  requires:
    - pip

about:
  home: https://rpaframework.org/
  summary: Core utilities used by RPA Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/rpaframework-core
