{% set name = "rpaframework-recognition" %}
{% set version = "5.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a238209c7e3081a221b75646fe75525f3cad7fd3e42cb5dbfd266c7526ea3b4e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<4.0
    - numpy 1.14.*
  run:
    - {{ pin_compatible('numpy') }}
    - opencv >=4.4.0,<5.0.0
    - pillow >=8.0.1,<9.0.0
    - pytesseract >=0.3.6,<0.4.0
    - python >=3.6,<4.0
    - rpaframework-core >=4.0.1,<5.0.0
    - tesseract >=4.1.1,<5.0.0

test:
  imports:
    - RPA
    - RPA.recognition
    # The package's requirements.txt has a different, too narrow numpy specification
    # commands:
      # - pip check
  requires:
    - pip

about:
  home: https://rpaframework.org/
  summary: Core utilities used by RPA Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/rpaframework-core
